FROM centos:7 as build
RUN mkdir -p /root/rpmbuild/SPECS && mkdir -p /root/tmp
COPY agent/rke2-agent.spec /root/rpmbuild/SPECS/rke2-agent.spec
COPY agent/rke2-agent.service /root/tmp/rke2-agent.service
COPY agent/rke2-agent.env /root/tmp/rke2-agent.env

COPY scripts scripts
RUN scripts/build-setup

ARG TAG
ENV TAG $TAG

ARG COMMIT
ENV COMMIT $COMMIT

RUN scripts/build-agent

FROM scratch
COPY --from=build /root/rpmbuild/RPMS/x86_64 /x86_64/