FROM centos:7 as build
RUN mkdir -p /root/rpmbuild/SPECS && mkdir -p /root/tmp
COPY server/rke2-server.spec /root/rpmbuild/SPECS/rke2-server.spec
COPY server/rke2-server.service /root/tmp/rke2-server.service
COPY server/rke2-server.env /root/tmp/rke2-server.env

COPY scripts scripts
RUN scripts/build-setup

ARG TAG
ENV TAG $TAG

ARG COMMIT
ENV COMMIT $COMMIT

RUN scripts/build-server

FROM scratch
COPY --from=build /root/rpmbuild/RPMS/x86_64 /x86_64/